# -*- coding: utf-8 -*-
"""1630.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jinGURxHA76sQan50vjub4iligKixoHE
"""

#Q16 Aim: To detect and count objects using segmentation. • Perform thresholding • Apply connected components • Count objects
import cv2, numpy as np, matplotlib.pyplot as plt

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg',0)

_,th = cv2.threshold(img,127,255,cv2.THRESH_BINARY)

n,labels = cv2.connectedComponents(th)   # Connected components

plt.imshow(labels,cmap='nipy_spectral')
plt.title('Objects = ' + str(n-1))       # subtract background
plt.axis('off')

#Q17 Aim: To analyze object detection using bounding boxes. • Detect components • Draw bounding boxes • Display output
import cv2, numpy as np, matplotlib.pyplot as plt

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

_,th = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)

n,labels,stats,_ = cv2.connectedComponentsWithStats(th)

for i in range(1,n):                         # skip background
    x,y,w,h,area = stats[i]
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title('Bounding Boxes')
plt.axis('off')

#Q18 Aim: To study effect of noise on segmentation. • Add noise • Perform segmentation • Apply filtering and re-segment
import cv2, numpy as np, matplotlib.pyplot as plt

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg',0)

# Add salt & pepper noise
noise = np.random.choice([0,255,None], img.shape, p=[0.02,0.02,0.96])
noisy = img.copy(); noisy[noise==0]=0; noisy[noise==255]=255

th1 = cv2.threshold(noisy,127,255,cv2.THRESH_BINARY)[1]   # Segmentation (noisy)

filt = cv2.medianBlur(noisy,3)                            # Filtering
th2 = cv2.threshold(filt,127,255,cv2.THRESH_BINARY)[1]    # Re-segmentation

plt.subplot(131),plt.imshow(th1,cmap='gray'),plt.title('Noisy Seg')
plt.subplot(132),plt.imshow(filt,cmap='gray'),plt.title('Filtered')
plt.subplot(133),plt.imshow(th2,cmap='gray'),plt.title('Clean Seg')
plt.show()

#Q19 Aim: To integrate morphology and segmentation. • Apply morphology • Perform segmentation • Compare accuracy
import cv2, numpy as np, matplotlib.pyplot as plt

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg',0)

# Direct segmentation
th1 = cv2.threshold(img,127,255,cv2.THRESH_BINARY)[1]

# Morphology (opening) + segmentation
k = np.ones((3,3),np.uint8)
prep = cv2.morphologyEx(img, cv2.MORPH_OPEN, k)
th2 = cv2.threshold(prep,127,255,cv2.THRESH_BINARY)[1]

plt.subplot(131),plt.imshow(th1,cmap='gray'),plt.title('Direct Seg')
plt.subplot(132),plt.imshow(prep,cmap='gray'),plt.title('After Morph')
plt.subplot(133),plt.imshow(th2,cmap='gray'),plt.title('Improved Seg')
plt.show()

#Q20 Aim: To extract texture features using GLCM. • Compute GLCM • Extract features (contrast, energy, etc.)
import cv2, numpy as np
from skimage.feature import graycomatrix, graycoprops

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg',0)

glcm = graycomatrix(img, distances=[1], angles=[0], levels=256, symmetric=True, normed=True)

contrast = graycoprops(glcm,'contrast')[0,0]
energy = graycoprops(glcm,'energy')[0,0]
homogeneity = graycoprops(glcm,'homogeneity')[0,0]

print("Contrast:",contrast)
print("Energy:",energy)
print("Homogeneity:",homogeneity)

#Q21 Aim: To analyze local texture using LBP. • Apply LBP • Display texture image • Analyze patterns
import cv2, matplotlib.pyplot as plt
from skimage.feature import local_binary_pattern

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg',0)

lbp = local_binary_pattern(img, P=8, R=1, method='uniform')

plt.subplot(121),plt.imshow(img,cmap='gray'),plt.title('Original')
plt.subplot(122),plt.imshow(lbp,cmap='gray'),plt.title('LBP')
plt.show()

#Q22 Aim: To compare GLCM and LBP features. • Extract both features • Compare results
import cv2, numpy as np
from skimage.feature import graycomatrix, graycoprops, local_binary_pattern

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg',0)

# GLCM
glcm = graycomatrix(img,[1],[0],256,True,True)
contrast = graycoprops(glcm,'contrast')[0,0]

# LBP
lbp = local_binary_pattern(img,8,1,'uniform')

print("GLCM Contrast:",contrast)
print("LBP Mean:",np.mean(lbp))

# Compare results
if contrast > np.mean(lbp):
    print("GLCM Contrast is higher than LBP Mean.")
elif contrast < np.mean(lbp):
    print("LBP Mean is higher than GLCM Contrast.")
else:
    print("GLCM Contrast and LBP Mean are equal.")

#Q23 Aim: To perform feature reduction using PCA. • Extract features • Apply PCA • Reduce dimensions
import cv2, numpy as np
from sklearn.decomposition import PCA

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg',0)

X = img.reshape(-1,1)            # flatten features

pca = PCA(n_components=1)
X_pca = pca.fit_transform(X)     # reduce dimension

print("Original shape:", X.shape)
print("Reduced shape:", X_pca.shape)

#Q24 Aim: To study effect of preprocessing on feature extraction. • Apply filtering • Extract GLCM features • Compare results
import cv2, numpy as np
from skimage.feature import graycomatrix, graycoprops

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg',0)

# Without preprocessing
g1 = graycomatrix(img,[1],[0],256,True,True)
c1 = graycoprops(g1,'contrast')[0,0]

# With filtering (Gaussian)
filt = cv2.GaussianBlur(img,(5,5),0)
g2 = graycomatrix(filt,[1],[0],256,True,True)
c2 = graycoprops(g2,'contrast')[0,0]

print("Contrast without filter:",c1)
print("Contrast with filter:",c2)

#Q25 Aim: To design a complete image processing pipeline. • Preprocessing • Segmentation • Feature extraction
import cv2, numpy as np
from skimage.feature import graycomatrix, graycoprops

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg',0)

# 1. Preprocessing (noise removal)
filt = cv2.GaussianBlur(img,(5,5),0)

# 2. Segmentation
th = cv2.threshold(filt,127,255,cv2.THRESH_BINARY)[1]

# 3. Feature Extraction (GLCM)
glcm = graycomatrix(th,[1],[0],256,True,True)
contrast = graycoprops(glcm,'contrast')[0,0]

print("Extracted Feature (Contrast):",contrast)

#Q26 Aim: To analyze resolution impact on feature extraction. • Downsample image • Extract features • Compare
import cv2, numpy as np
from skimage.feature import graycomatrix, graycoprops

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg',0)

# Downsample image
low = cv2.resize(img,None,fx=0.5,fy=0.5)

# GLCM features
g1 = graycomatrix(img,[1],[0],256,True,True)
g2 = graycomatrix(low,[1],[0],256,True,True)

c1 = graycoprops(g1,'contrast')[0,0]
c2 = graycoprops(g2,'contrast')[0,0]

print("Original Contrast:",c1)
print("Low Res Contrast:",c2)

#Q27 Aim: To compare spatial, frequency, and morphological processing. • Apply each method • Analyze differences
import cv2, numpy as np, matplotlib.pyplot as plt

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg',0)

# Spatial (Gaussian)
sp = cv2.GaussianBlur(img,(5,5),0)

# Frequency (Low Pass)
f = np.fft.fftshift(np.fft.fft2(img))
r,c = img.shape; m = np.zeros((r,c),np.uint8)
m[r//2-30:r//2+30, c//2-30:c//2+30] = 1
fr = np.abs(np.fft.ifft2(np.fft.ifftshift(f*m)))

# Morphology (Opening)
k = np.ones((3,3),np.uint8)
mo = cv2.morphologyEx(img, cv2.MORPH_OPEN, k)

plt.subplot(141),plt.imshow(img,cmap='gray'),plt.title('Original')
plt.subplot(142),plt.imshow(sp,cmap='gray'),plt.title('Spatial')
plt.subplot(143),plt.imshow(fr,cmap='gray'),plt.title('Frequency')
plt.subplot(144),plt.imshow(mo,cmap='gray'),plt.title('Morphology')
plt.show()

#Q28 Aim: To perform end-to-end image analysis. • Noise removal • Segmentation • Feature extraction • Dimensionality reduction
import cv2, numpy as np
from skimage.feature import graycomatrix, graycoprops
from sklearn.decomposition import PCA

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg',0)

# 1. Noise removal
filt = cv2.medianBlur(img,3)

# 2. Segmentation
th = cv2.threshold(filt,127,255,cv2.THRESH_BINARY)[1]

# 3. Feature extraction (GLCM)
glcm = graycomatrix(th,[1],[0],256,True,True)
feat = graycoprops(glcm,'contrast')[0,0]

# 4. Dimensionality reduction (PCA)
X = np.array([[feat]])
pca = PCA(n_components=1)
X_pca = pca.fit_transform(X)

print("Feature:",feat)
print("Reduced Feature:",X_pca)

#Q29 Aim: To apply and analyze Watershed Thresholding for image segmentation. • Convert the input image to grayscale. • Apply gradient-based edge detection. • Use Watershed algorithm to segment the image based on gradients. • Visualize and label the segmented regions.
import cv2, numpy as np, matplotlib.pyplot as plt

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Threshold + noise removal
_,th = cv2.threshold(gray,0,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)
k = np.ones((3,3),np.uint8)
opening = cv2.morphologyEx(th, cv2.MORPH_OPEN, k)

# Sure background & foreground
bg = cv2.dilate(opening,k,3)
dist = cv2.distanceTransform(opening,cv2.DIST_L2,5)
_,fg = cv2.threshold(dist,0.7*dist.max(),255,0)

# Markers + Watershed
fg = np.uint8(fg)
unknown = cv2.subtract(bg,fg)
_,markers = cv2.connectedComponents(fg)
markers = markers + 1
markers[unknown==255] = 0

markers = cv2.watershed(img,markers)
img[markers==-1] = [255,0,0]   # boundaries

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title('Watershed Segmentation')
plt.axis('off')

#Q30 Aim: To perform Otsu’s Thresholding for image segmentation and compare results. • Convert the image to grayscale. • Apply Otsu’s method for automatic thresholding. • Segment the image using the computed threshold value. • Compare the result with manual thresholding.
import cv2, matplotlib.pyplot as plt

img = cv2.imread('/content/dwayne-joe-rLLP1G4ZRT0-unsplash.jpg',0)

# Manual threshold
_,th1 = cv2.threshold(img,127,255,cv2.THRESH_BINARY)

# Otsu threshold
_,th2 = cv2.threshold(img,0,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)

plt.subplot(131),plt.imshow(img,cmap='gray'),plt.title('Original')
plt.subplot(132),plt.imshow(th1,cmap='gray'),plt.title('Manual')
plt.subplot(133),plt.imshow(th2,cmap='gray'),plt.title('Otsu')
plt.show()